### PR TITLE
COG-1404: Use NULLIDT1 package in DB2 Connection Properties - CAP Users Job

### PR DESCRIPTION
**Pull request by dmytro-palczewski-osi**

### CODE REVIEW

**Comment by dmytro-palczewski-osi** [comment]
retest this please

**Comment by dmytro-palczewski-osi** [comment]
retest this please

**Comment by dmytro-palczewski-osi** [comment]
retest this please

**Comment by AlexanderSerbin** [comment]
Closing as already unneeded

**Pull request closed without merging**
