### PR TITLE
SEAR-597: Hotfix - Implement new schema changes in Integration for LIS database

### PR DESCRIPTION
**Pull request by pradipforever**
### JIRA Issue Link
- https://osi-cwds.atlassian.net/browse/SEAR-597

Hotfix - Implement new schema changes in Integration for LIS database.

### CODE REVIEW

**Comment by AlexanderSerbin** [comment]
Please retest this

**Comment by AlexanderSerbin** [comment]
Retest this please

**Comment by pradipforever** [comment]
retest this please.

**Comment by pradipforever** [comment]
retest this please.

**Pull request merged**
