### PR TITLE
FIT-291 Implement-Semantic-Versioning-Support-for-CALS-Job, add jenki…

### PR DESCRIPTION
**Pull request by mariamcws**
…ns-pipeline-utils

First cut for this story

## Description
Implement Semantic Versioning Support for cwds-jobs

[Implement Semantic Versioning Support for CALS-Job](https://osi-cwds.atlassian.net/browse/FIT-291)

## Types of changes
- [x] New feature (non-breaking change for continuous integration)

### CODE REVIEW

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by mariamcws** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Pull request merged**
